### ISSUE TITLE
Add copyright notice regarding brand trademark

### ISSUE THREAD

**Issue by pires** [superevilbananaoverlord/porquinhoninja#2]
One should add the following copyright notice 

```
Porquinho Ninja trademark is owned by Paulo Pires (@pires)
```

**Comment by superevilbananaoverlords** [comment]
Yeah right, like we care. We can do whatever we want.

**Comment by superevilbananaoverlords** [comment]
Okay.

**Comment by pires** [comment]
You could have closed this with your PR. Just needed to add `Fixes #1` to commit log, you [lammer](http://www.urbandictionary.com/define.php?term=lammer).

**Comment by superevilbananaoverlords** [comment]
Mimimimi bububu.

We know how to use `git`, `GitHub`, `commits` and `issues` but we don't [give a fuck](http://www.urbandictionary.com/define.php?term=give+a+fuck).

**Comment by pires** [comment]
You're a good lammer, indeed.

**Comment by superevilbananaoverlords** [comment]
Thanks, bro :)
